# Generated by Django 2.2.5 on 2023-07-11 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20230710_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
