# Generated by Django 2.2.5 on 2023-07-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20230711_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Leave_type',
            field=models.CharField(choices=[('S', 'Sick Leave'), ('A', 'Annual Leave'), ('P', 'Personal Leave')], default=None, max_length=1),
        ),
    ]
