# Generated by Django 2.2.5 on 2023-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20230711_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='end',
            field=models.DateTimeField(default='2023-07-11 16:35'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='start',
            field=models.DateTimeField(default='2023-07-11 16:35'),
        ),
    ]
